# Generated by Django 4.0.4 on 2022-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_topic_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.SlugField(default='dafault_url'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
