# Generated by Django 4.0.4 on 2022-06-13 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0004_article_url_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.SlugField(default='dafault_url', unique=True),
        ),
    ]
