# Generated by Django 4.0.4 on 2022-06-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_topic_author_alter_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
    ]
